#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

//Change when updating smith
constexpr const char* SMITH_VERSION = "0.1.0";

void print_help(const char* program_name) {
  std::cout
    << "Usage:\n"
    << "  " << program_name << " ProjectName\n"
    << "  " << program_name << " --help\n"
    << "  " << program_name << " --version\n\n"
    << "Options:\n"
    << "  --help      Show this help message\n"
    << "  --version   Print version information\n";
}

void print_version() {
  std::cout << "smith version: " << SMITH_VERSION << std::endl;
}

bool write_file(const std::string& path, const std::string& contents) {
  std::ofstream out(path);
  if (!out) {
    return false;
  }
  out << contents;
  return static_cast<bool>(out);
}

namespace fs = std::filesystem;

// built in templates
const std::string main_template = R"(
#include <iostream>

int main() {
  std::cout << "Hello, Smith project!" << std::endl;
  return 0;
}
)";

const std::string cmake_template = R"(
cmake_minimum_required(VERSION 3.16)
project(MyProject)

set(CMAKE_CXX_STANDARD 17)

add_executable(MyProject src/main.cpp)
)";

const std::string readme_template = R"(
  This project was created using Smith, a minimal C++ project generator.
)";

const std::string gitignore_template = R"(
  # Build directories generated by CMake
  build/
  Debug/
  Release/
  x64/
  bin/
  lib/
)";

const std::string test_template = R"(
  #include <iostream>
  int main() {
    std::cout << "Running tests for PROJECT_NAME..." << std::endl;
    return 0;
  }
)";


// replace template strings with project name
std::string replace_project_name(const std::string& template_string, const std::string& project_name) {
  std::string result = template_string;
  size_t pos = 0;
  while ((pos = result.find("PROJECT_NAME", pos)) != std::string::npos) {
    result.replace(pos, 9, project_name);
    pos += project_name.length();
  }
  return result;
}


int main(int argc, char** argv) {
  if (argc < 2) {
    print_help(argv[0]);
    return 1;
  }

  std::string arg = argv[1];

  if (arg == "--help") {
    print_help(argv[0]);
    return 0;
  }

  if (arg == "--version") {
    print_version();
    return 0;
  }

  std::string project = argv[1];
  fs::create_directories(project + "/src");
  fs::create_directories(project + "/include");
  fs::create_directories(project + "/tests");

  // create files replacing project name
  std::ofstream(project + "/src/main.cpp") << replace_project_name(main_template, project);
  std::ofstream(project + "/CMakeLists.txt") << replace_project_name(cmake_template, project);
  std::ofstream(project + "/README.md") << replace_project_name(readme_template, project);
  std::ofstream(project + "/.gitignore") << replace_project_name(gitignore_template, project);
  std::ofstream(project + "/tests/test.cpp") << replace_project_name(test_template, project);

  std::cout << "Project created successfully: " << project << std::endl;
  std::cout << "Run 'cd " << project << " && cmake .. && make' to build the project." << std::endl;

  return 0;
}
