#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <ctime>


//Change when updating smith
constexpr const char* SMITH_VERSION = "0.1.0";

void print_help(const char* program_name) {
  std::cout
    << "Usage:\n"
    << "  " << program_name << " ProjectName\n"
    << "  " << program_name << " --help\n"
    << "  " << program_name << " --version\n\n"
    << "Options:\n"
    << "  --help      Show this help message\n"
    << "  --version   Print version information\n";
}

void print_version() {
  std::cout << "smith version: " << SMITH_VERSION << std::endl;
}


namespace fs = std::filesystem;

// built in templates
const std::string main_template = R"(
#include <iostream>

int main() {
  std::cout << "Hello, Smith project!" << std::endl;
  return 0;
}
)";

const std::string cmake_template = R"(
cmake_minimum_required(VERSION 3.16)
project(MyProject)

set(CMAKE_CXX_STANDARD 17)

add_executable(MyProject src/main.cpp)
)";

const std::string readme_template = R"(
  This project was created using Smith, a minimal C++ project generator.
)";

const std::string gitignore_template = R"(
  # Build directories generated by CMake
  build/
  Debug/
  Release/
  x64/
  bin/
  lib/
)";

const std::string test_template = R"(
  #include <iostream>
  int main() {
    std::cout << "Running tests for PROJECT_NAME..." << std::endl;
    return 0;
  }
)";

const std::string license_template = R"(MIT License

Copyright (c) [year]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
)";

// replace template strings with project name
std::string replace_project_name(const std::string& template_string, const std::string& project_name) {
  std::string result = template_string;
  size_t pos = 0;
  while ((pos = result.find("PROJECT_NAME", pos)) != std::string::npos) {
    result.replace(pos, 12, project_name); // Used to be 9
    pos += project_name.length();
  }
  return result;
}

std::string replace_year_name(const std::string& template_string) {
  std::string result = template_string;
  std::time_t time = std::time(nullptr);
  std::tm* now = std::localtime(&time);
  std::string year_name = std::to_string(now->tm_year + 1900);

  size_t pos = 0;
  while ((pos = result.find("[year]", pos)) != std::string::npos) {
    result.replace(pos, 6, year_name);
    pos += year_name.length();
  }

  return result;
}


int main(int argc, char** argv) {
  if (argc < 2) {
    print_help(argv[0]);
    return 1;
  }

  std::string arg = argv[1];

  if (arg == "--help") {
    print_help(argv[0]);
    return 0;
  }

  if (arg == "--version") {
    print_version();
    return 0;
  }

  fs::create_directories(arg + "/src");
  fs::create_directories(arg + "/include");
  fs::create_directories(arg + "/tests");

  // create files replacing project name
  std::ofstream(arg + "/src/main.cpp") << replace_project_name(main_template, arg);
  std::ofstream(arg + "/CMakeLists.txt") << replace_project_name(cmake_template, arg);
  std::ofstream(arg + "/README.md") << replace_project_name(readme_template, arg);
  std::ofstream(arg + "/.gitignore") << replace_project_name(gitignore_template, arg);
  std::ofstream(arg + "/tests/test.cpp") << replace_project_name(test_template, arg);

  // create LICENSE file replacing the year with current year
  std::ofstream(arg + "/LICENSE") << replace_year_name(license_template);

  std::cout << "Project created successfully: " << arg << std::endl;
  std::cout << "Run 'cd " << arg << " && cmake .. && make' to build the project." << std::endl;

  return 0;
}
